<?php

/**
 * Implements of hook_services_resources().
 */
function expressInterest_services_resources() {
	
  $definition = array(
    'expressInterest' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieve a expressInterest gallery',
          'callback' => '_editProfile_resource_retrieve',
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'profile',
              'type' => 'array',
              'description' => 'The uid of the expressInterest to retrieve.',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
          ),
        ),

        'create' => array(
          'help' => 'Create a expressInterest',
          'callback' => '_expressInterest_resource_create',
          'access callback' => '_expressInterest_resource_access',
          'access arguments' => array('create'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'account',
              'type' => 'array',
              'description' => 'The expressInterest object',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
		'delete' => array(
          'help' => 'Delete a profile',
          'callback' => '_expressInterest_resource_delete',
          'access callback' => '_expressInterest_resource_access',
          'access arguments' => array('edit'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'The id of the comment to delete',
              'source' => array('path' => '0'),
              'optional' => FALSE,
            ),
          ),
        ),
        'index' => array(
          'help' => 'List all expressInterest',
          'callback' => '_expressInterest_resource_index',
          'args' => array(
            array(
              'name' => 'page',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'The zero-based index of the page to get, defaults to 0.',
              'default value' => 0,
              'source' => array('param' => 'page'),
            ),
            array(
              'name' => 'fields',
              'optional' => TRUE,
              'type' => 'string',
              'description' => 'The fields to get.',
              'default value' => '*',
              'source' => array('param' => 'fields'),
            ),
            array(
              'name' => 'parameters',
              'optional' => TRUE,
              'type' => 'array',
              'description' => 'Parameters',
              'default value' => array(),
              'source' => array('param' => 'parameters'),
            ),
            array(
              'name' => 'pagesize',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'Number of records to get per page.',
              'default value' => variable_get('services_expressInterest_index_page_size', 20),
              'source' => array('param' => 'pagesize'),
            ),
          ),
          'access arguments' => array('access expressInterest profiles'),
          'access arguments append' => FALSE,
        ),
      ),     
    ),
  );

  $definition['expressInterest']['actions']['register'] = array_merge($definition['expressInterest']['operations']['create'], array(
    'help' => 'Register a expressInterest',
  ));

  return $definition;
	
}

function _expressInterest_resource_retrieve($uid){	
	return $res = _expressInterest_resource_delete($_REQUEST['uid']);
	 
}

function _expressInterest_resource_access(){
	return true;
}

function _expressInterest_resource_delete($uid){

	$query = db_update('users')->fields(array('status' => 0))->condition('uid', $uid, '=')->execute();
	$result = db_truncate('cache_field')->execute();
	
	if($query){
		$response['msg'] = 'Profile deleted successfully';			
		db_cache_clear_all();		
		$respo = json_encode($response);
		return $respo;
	}
		
}


function _expressInterest_resource_create($arg1){
	//print_r($arg1);exit;	
	$uid = $arg1['user'];
	$interest_to = $arg1['interest_to'];
	
	$sql = db_select('express_interest', 'e')->fields('e')->condition('uid' , $uid, '=')->condition('interest_to_uid' , $interest_to, '=')->execute()->fetchAssoc();
		//print_r($sql); exit;
	if($arg1['interest_flag'] == 'check'){	
		if(empty($sql)){
			return true;
		}else{
			return false;
		}	
	}
	
	
	if(empty($sql)){
	$con = db_insert('express_interest')->fields(array(			
						'uid' => $uid,
						'interest_to_uid' => $interest_to,
						'status' => 0,
						'created' => REQUEST_TIME,
						'changed' => REQUEST_TIME,	
					))->execute();
	//echo $con; exit;		
	}
	return true;
}

?>