<?php

function custModule_form_profile2_edit_main_form_alter(&$form, &$form_state) {
  $form['profile_main']['field_height_inches']['und']['#access'] = 0;
  $form['profile_main']['field_age']['und']['#access'] = 0;
  return $form;
}


function custModule_profile2_presave($profile) {
  $height = $profile->field_height['und'][0]['value'];
  $heightInFoot = explode(".", $height);
  $heightInInches = ($heightInFoot[0]*12) + $heightInFoot[1];
  $profile->field_height_inches['und'][0]['value'] = $heightInInches;
  $profile->field_age['und'][0]['value'] = getAge($profile->field_birth_date['und']['0']['value']);
}



function convertTO($height, $feet=FALSE, $inches= FALSE) {
	if ($inches) {
	  $height = $height%12;
	}
	else {
	  $height = $height/12;
	}
	  return $height;
}

function getAge($dob) 
{ 	
	if ($dob) {
		$from = new DateTime($dob);
		$to   = new DateTime('today');
		$age = $from->diff($to)->y;
	}
    return $age; 
}