<?php

/**
 * Implements of hook_services_resources().
 */
function editProfile_services_resources() {
	
  $definition = array(
    'editProfile' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieve a editProfile',
          'callback' => '_editProfile_resource_retrieve',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'The uid of the editProfile to retrieve.',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
          ),
        ),

        'create' => array(
          'help' => 'Create a editProfile',
          'callback' => '_editProfile_resource_create',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('create'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'account',
              'type' => 'array',
              'description' => 'The editProfile object',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),

        'update' => array(
          'help' => 'Update a editProfile',
          'callback' => '_editProfile_resource_update',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('update'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'Unique identifier for this editProfile',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'The editProfile object with updated information',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),

        'delete' => array(
          'help' => 'Delete a editProfile',
          'callback' => '_editProfile_resource_delete',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('delete'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'The id of the editProfile to delete',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
          ),
        ),
        'index' => array(
          'help' => 'List all editProfiles',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'callback' => '_editProfile_resource_index',
          'args' => array(
            array(
              'name' => 'page',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'The zero-based index of the page to get, defaults to 0.',
              'default value' => 0,
              'source' => array('param' => 'page'),
            ),
            array(
              'name' => 'fields',
              'optional' => TRUE,
              'type' => 'string',
              'description' => 'The fields to get.',
              'default value' => '*',
              'source' => array('param' => 'fields'),
            ),
            array(
              'name' => 'parameters',
              'optional' => TRUE,
              'type' => 'array',
              'description' => 'Parameters',
              'default value' => array(),
              'source' => array('param' => 'parameters'),
            ),
            array(
              'name' => 'pagesize',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'Number of records to get per page.',
              'default value' => variable_get('services_editProfile_index_page_size', 20),
              'source' => array('param' => 'pagesize'),
            ),
          ),
          'access arguments' => array('access editProfile profiles'),
          'access arguments append' => FALSE,
        ),
      ),
      'actions' => array(
        'login' => array(
          'help' => 'Login a editProfile for a new session',
          'callback' => '_editProfile_resource_login',
          'args' => array(
            array(
              'name' => 'editProfilename',
              'type' => 'string',
              'description' => 'A valid editProfilename',
              'source' => array('data' => 'editProfilename'),
              'optional' => FALSE,
            ),
            array(
              'name' => 'password',
              'type' => 'string',
              'description' => 'A valid password',
              'source' => array('data' => 'password'),
              'optional' => FALSE,
            ),
          ),
          'access callback' => 'services_access_menu',
          'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
        ),
        'logout' => array(
          'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'help' => 'Logout a editProfile session',
          'callback' => '_editProfile_resource_logout',
          'access callback' => 'services_access_menu',
        ),
        'token' => array(
          'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'callback' => '_editProfile_resource_get_token',
          'access callback' => 'services_access_menu',
          'help' => t('Returns the CSRF token.'),
        ),
        'request_new_password' => array(
          'help' => 'Request a new password, given a editProfile name or e-mail address',
          'callback' => '_editProfile_resource_request_new_password',
          'args' => array(
            array(
              'name' => 'name',
              'type' => 'string',
              'description' => 'A valid editProfile name or e-mail address',
              'source' => array('data' => 'name'),
              'optional' => FALSE,
            ),
          ),
          'access callback' => 'services_access_menu',
          'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
        ),
      ),
      'targeted_actions' => array(
        'cancel' => array(
          'help' => 'Cancel a editProfile',
          'callback' => '_editProfile_resource_cancel',
          //'file' => array('type' => 'inc', 'module' => 'services', 'name' => 'resources/editProfile_resource'),
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('cancel'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'The id of the editProfile to cancel.',
            ),
          ),
        ),
        'password_reset' => array(
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('password_reset'),
          'access arguments append' => TRUE,
          'callback' => '_editProfile_resource_password_reset',
          'args' => array(
            array(
              'name' => 'uid',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'The id of the editProfile whose password to reset.',
            ),
          ),
        ),
        'resend_welcome_email' => array(
          'access callback' => '_editProfile_resource_access',
          'access arguments' => array('resend_welcome_email'),
          'access arguments append' => TRUE,
          'callback' => '_editProfile_resource_resend_welcome_email',
          'args' => array(
            array(
              'name' => 'uid',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'The id of the editProfile whose welcome email to resend.',
            ),
          ),
        ),
      ),
    ),
  );

  $definition['editProfile']['actions']['register'] = array_merge($definition['editProfile']['operations']['create'], array(
    'help' => 'Register a editProfile',
  ));

  return $definition;
	
}

function _editProfile_resource_access(){
	echo "_editProfile_resource_access";
	return true;
}

function _editProfile_resource_create(){
	echo "_editProfile_resource_create";
	echo "done";exit;
	return true;
}

function _editProfile_resource_update(){
	echo "_editProfile_resource_update";
	echo "sneha done";exit;
	return "hi, this is my post request ".$arg1;
}


?>