<?php

/**
 * Implements of hook_services_resources().
 */
function editProfile_services_resources() {
	
	return /*array(
		'editprofile' => array(
		      'create' => array(
        'callback' => '_editProfile_create',
        'args' => array(
          array(
            'name' => 'arg1',
            'optional' => FALSE,
            'source' => array('path' => 0),
            'type' => 'int',
            'description' => 'Test argument 1.',
          ),
        ),
        'access callback' => '_editProfile_access',
        'access arguments' => array('view'),
        'access arguments append' => TRUE,
      ),
			'actions' => array(
				'action_retrieve' => array(
				'callback' => '_editProfile_action_create',
				'args' => array(
					array(
					  'name' => 'arg1',
					  'optional' => FALSE,
					  'source' => array('path' => 1),
					  'type' => 'int',
					  'description' => 'Test argument 1.',
					),
				),
				'access callback' => '_editProfile_access',
				'access arguments' => array('access content'),
				'access arguments append' => TRUE,
				),
			),
		),	
	);	*/
	
	
	
	 array(
    'editProfile' => array(
      'retrieve' => array(
        'help' => 'Retrieves a note',
        //'file' => array('file' => 'inc', 'module' => 'editProfile'),
        'callback' => '_editProfile_retrieve',
        'access callback' => '_editProfile_access',
        //'access arguments' => array('view'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The id of the note to get',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
        ),
      ),
      'actions' => array(
          'create' => array(
            'help' => 'Creates a note',
           // 'file' => array('file' => 'inc', 'module' => 'editProfile'),
            'callback' => '_editProfile_create',
            //'access arguments' => array('editProfile resource create'),
			'access arguments' => TRUE,
            'access arguments append' => FALSE,
            'args' => array(
              array(
                'name' => 'data',
                'type' => 'struct',
                'description' => 'The note object',
                'source' => 'data',
                'optional' => FALSE,
              ),
            ),
          ),
      ),
      'update' => array(
        'help' => 'Updates a note',
        //'file' => array('file' => 'inc', 'module' => 'editProfile'),
        'callback' => '_editProfile_update',
        'access callback' => '_editProfile_access',
        'access arguments' => array('update'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The id of the node to update',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
          array(
            'name' => 'data',
            'type' => 'struct',
            'description' => 'The note data object',
            'source' => 'data',
            'optional' => FALSE,
          ),
        ),
      ),
      'delete' => array(
        'help' => 'Deletes a note',
        //'file' => array('file' => 'inc', 'module' => 'editProfile'),
        'callback' => '_editProfile_delete',
        'access callback' => '_editProfile_access',
        'access arguments' => array('delete'),
        'access arguments append' => TRUE,
        'args' => array(
          array(
            'name' => 'nid',
            'type' => 'int',
            'description' => 'The id of the note to delete',
            'source' => array('path' => '0'),
            'optional' => FALSE,
          ),
        ),
      ),
      'index' => array(
        'help' => 'Retrieves a listing of notes',
        //'file' => array('file' => 'inc', 'module' => 'editProfile'),
        'callback' => '_editProfile_index',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'page',
            'type' => 'int',
            'description' => '',
            'source' => array(
              'param' => 'page',
            ),
            'optional' => TRUE,
            'default value' => 0,
          ),
          array(
           'name' => 'parameters',
           'type' => 'array',
           'description' => '',
           'source' => 'param',
           'optional' => TRUE,
           'default value' => array(),
          ),
        ),
      ),
	  'targeted_actions' => array(
        'test' => array(
          'access callback' => '_editProfile_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'callback' => '_editProfile_targeted_action_test',
          'args' => array(
            array(
              'name' => 'arg1',
              'optional' => FALSE,
              'source' => array('path' => 0),
              'type' => 'int',
              'description' => 'Test argument 1.',
            ),
          ),
        ),
      ),
    ),
  );
	
}

function _editProfile_access(){
	return true;
}

function _editProfile_targeted_action_test(){
	echo "done";exit;
	return true;
}

function _editProfile_create(){
	echo "sneha done";exit;
	return "hi, this is my post request ".$arg1;
}


?>