<?php

/**
 * Implements of hook_services_resources().
 */
function editProfilePics_services_resources() {
	
  $definition = array(
    'editProfilePics' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieve a editProfilePics',
          'callback' => '_editProfilePics_resource_retrieve',
          'access callback' => '_editProfilePics_resource_access',
          'access arguments' => array('view'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'profile',
              'type' => 'array',
              'description' => 'The uid of the editProfilePics to retrieve.',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
          ),
        ),

        'create' => array(
          'help' => 'Create a editProfilePics',
          'callback' => '_editProfilePics_resource_create',
          'access callback' => '_editProfilePics_resource_access',
          'access arguments' => array('create'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'account',
              'type' => 'array',
              'description' => 'The editProfilePics object',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
		
      ),     
    ),
  );

  return $definition;
	
}

function _editProfilePics_resource_retrieve($uid){
	//print_r($_REQUEST);exit;
	return $res = _editProfilePics_resource_delete($_REQUEST);
	 
}

function _editProfilePics_resource_access(){
	return true;
}

function _editProfilePics_resource_delete($uid){

	//print_r($_REQUEST);
	$pData = get_pid($_REQUEST['user']);
	$pid = $pData['pid'];
	//exit;	
		
	if($_REQUEST['action'] == 'remove'){
		$query = db_update('file_managed')->fields(array('status' => 0))->condition('uid', $_REQUEST['user'], '=')->condition('fid', $_REQUEST['fid'], '=')->execute();
		
		$query1 = db_delete('file_usage')->condition('fid', $_REQUEST['fid'], '=')->condition('id', $pid, '=')->execute();
		$query2 = db_delete('field_revision_field_profile_img')->condition('field_profile_img_fid', $_REQUEST['fid'], '=')->condition('revision_id', $pid, '=')->condition('entity_id', $pid, '=')->execute();
		$query3 = db_delete('field_data_field_profile_img')->condition('field_profile_img_fid', $_REQUEST['fid'], '=')->condition('revision_id', $pid, '=')->condition('entity_id', $pid, '=')->execute();
		
	}	
	
	$result = db_truncate('cache_field')->execute();
	
	if($query){		
		db_cache_clear_all();		
		return true;
	}
		
}

function _editProfilePics_resource_create($arg1){
	print_r($arg1);exit;
	return true;
}


?>